### PR TITLE
install OCaml 4.14.1 by default

### LINKED ISSUE #13: Updating OCaml version
We're currently defaulting to OCaml 4.09.0, which locks us to lcaml-lsp-server 1.4.1 from March 2021. The current version of that is 1.17.0 which has an `ocaml >= 4.14`. However, we're also locked to camlp5 8.00 which has `ocaml < 4.13.0`, meaning `4.12.1`. This would allow us at most ocaml-lsp-server 1.8.3 from October 2021, which doesn't seem like much of an upgrade.

I just noticed that camlp5 8.00.03 is the last version that has [the patch](https://github.com/ocaml-opam/opam-repository-mingw/blob/sunset/packages/camlp5/camlp5.8.00.03/files/camlp5-rel8.00.03.patch) on the sunset repository, and coincidentally it's the first version that has `ocaml < 4.15.0`, which _should_ allow us an upgrade to 4.14.

I'll see if that works... The reason I'm opening this issue is mostly to rant, but also because my IDE currently looks like this:

Code_NqJSvOZZP6

I don't remember what versions I had before, so I'm trying to recreate to workable working environment.

### PR DESCRIPTION
**Pull request by Simn**
This should be tested on a clean system first. I saw some issue where it would try to reinstall camlp5 during the big dependency install at the end, which then caused the `# The -prefix directory must be absolute.` problem again. However, I don't really see how the current installation procedure would avoid this either.

There's some repo order juggling here because we need camlp5 from one repo but luv from another. I hope it works like that...

Closes #13

### CODE REVIEW

**Comment by Simn** [comment]
I'll go ahead and merge this because "it works for me". I still managed to somehow run into the camlp5 problem mentioned in #13, but that is not directly related to upgrading OCaml and can happen with 4.09 as well in some circumstances that have to be investigated.

Let me know if this breaks someone's setup.

**Comment by tobil4sk** [comment]
The last version of camlp5 that was patched in opam-repository-mingw is `8.00~alpha06`, which requires ocaml `>= "4.02" & < "4.12.0"`. The ocaml upgrade probably forces camlp5 to be updated too, to a version that is missing from opam-repository-mingw and thus has the prefix error.

**Comment by Simn** [comment]
I don't think that's the latest version that had the patch, it's just the one listed at the bottom. See https://github.com/HaxeFoundation/ocamhaxe/issues/13#issue-2069009366.

**Comment by tobil4sk** [comment]
Oh yeah, my bad I missed that!

**Pull request merged**
